Release/v1.1.0 (#19)
* feat: Add update check

* chore: Update pre-commit

* chore: package.json: Add install-local command

* v1.1.0

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,18 @@
+#!/bin/bash
+
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | xargs -r)
+
 if [ -n "$STAGED_FILES" ]; then
-  if ! npx prettier --check --ignore-unknown $STAGED_FILES; then
-    npx prettier --write --ignore-unknown $STAGED_FILES
+  if ! npx prettier --check --ignore-unknown $STAGED_FILES >/dev/null 2>&1; then
+    npx prettier --write --ignore-unknown $STAGED_FILES >/dev/null 2>&1
     echo "Formatting issues detected. Please stage the formatted files."
     exit 1
   fi
 fi
-if ! npm run lint; then
-  echo "Linting/typecheck issues detected."
+
+if ! npm run lint >/dev/null 2>&1; then
+  echo "Type check failed."
   exit 1
 fi
+
+echo "All checks passed."
